app/my_app/simulacro/models.py
from sqlalchemy.orm import relationship
from sqlalchemy import Column,String,Integer,DateTime
from my_app import db
from datetime import datetime
    
class Area(db.Model):
    __tablename__='areas'
    id=db.Column(db.Integer, primary_key=True)
    area=db.Column(db.String(255))
    p_total=db.Column(db.Integer,nullable=False)
    p_actual=db.Column(db.Integer,nullable=False)
    p_rezago=db.Column(db.Integer,nullable=True)
    created_at=db.Column(db.DateTime,default=datetime.utcnow)
    
class Historial(db.Model):
    __tablename__='historial'
    id=db.Column(db.Integer, primary_key=True)
    h_brigadista_id=db.Column(db.Integer, nullable=False)
    h_brigadista_name=db.Column(db.String(255), nullable=False)
    h_area_created_at=db.Column(db.DateTime,default=datetime.utcnow)
    h_area_id=db.Column(db.Integer, nullable=False)
    h_area_p_total=db.Column(db.Integer,nullable=False)
    h_area_p_actual=db.Column(db.Integer,nullable=False)
    h_area_p_rezago=db.Column(db.Integer,nullable=False)
    

app/my_app/simulacro/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,IntegerField
from wtforms.validators import InputRequired, DataRequired

class Evento(FlaskForm):
    p_actual=IntegerField ('Personal "Evacuado"', validators=[DataRequired()])
    p_rezago=IntegerField ('Personal en "Rezago"')

app/my_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from my_app.config import DevConfig, ProdConfig
from flask_bootstrap import Bootstrap5
from flask_migrate import Migrate
from flask_login import LoginManager


app=Flask(__name__)
app.config.from_object(DevConfig)
bootstrap = Bootstrap5(app)

db=SQLAlchemy(app)
migrate=Migrate(app,db)

login_manager=LoginManager()
login_manager.init_app(app)

from my_app.simulacro.controllers import simulacroRoute
app.register_blueprint(simulacroRoute)
from my_app.auth.controllers import authRoute
app.register_blueprint(authRoute)

app/my_app/simulacro/controllers.py
from flask import Blueprint, redirect, url_for, render_template, request,g,session
from my_app.simulacro.models import Area,Historial
from my_app.auth import models
from my_app.simulacro import forms 
from my_app.auth import controllers
from my_app.simulacro import operations
from my_app.auth import operations as operationsdb
from flask_login import login_required, current_user

simulacroRoute=Blueprint('simulacro',__name__,url_prefix='/simulacro')

task_list=[1,2,3,4,5,6]

@simulacroRoute.before_request
@login_required
def before():
    pass

@simulacroRoute.route('/')
# @login_required
def index():
    area=operations.getAll()
    username=controllers.current_user.username
    user_id=controllers.current_user.id
    b_id=Area.query.filter(Area.id.like(user_id)).all()
    return render_template('dashboard/index.html',user_id=user_id,
                                                b_id=b_id,
                                                username=username,
                                                area=area)

@simulacroRoute.route('/<int:id>')
def show(id:int):
    return 'la de show... ' + str(id)

@simulacroRoute.route('/delete/<int:id>')
def delete(id:int):
    operations.delete(id)
    return redirect(url_for('simulacro.index'))

@simulacroRoute.route('/create', methods=('GET','POST') )
def create():
    form=forms.Usuario()
    if form.validate_on_submit():
        print(form.name.data)
        operations.create(form.name.data)
    return render_template('dashboard/evento/create_user.html',form=form)

@simulacroRoute.route('/update/<int:id>', methods=('GET','POST') )
def update(id:int):
    
    evento=operations.getById(id)
    form=forms.Evento()
    
    if request.method=='GET':
        form.p_actual.data=evento.p_actual
        form.p_rezago.data=evento.p_rezago
    if form.validate_on_submit():
        operations.update(id,form.p_actual.data,form.p_rezago.data)
    
    return render_template('dashboard/evento/update.html',form=form)

@simulacroRoute.route('/monitor')
def monitor():
    username=controllers.current_user.username
    user=operationsdb.getAll()
    print(user)
    print(username)
    return render_template('dashboard/monitor.html',username=username,user=user)

app/my_app/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}{% endblock title %} </title>
</head>
<header>
</header>
<body>
    {{bootstrap.load_css()}}


    {% block content %}  
    {% endblock content %}

{{bootstrap.load_js()}}
</body>
</html>

app/my_app/templates/dashboard/evento/create_user.html
{% extends 'dashboard/base.html' %}



{% block title %}create_user{% endblock title %}

{% block content %}
<br>
<div class="container" >
    <form action="" method="post">
        {{ form.name.label }}
        {{ form.name }}
        {{ form.csrf_token }}
        <button type="submit">Enviar</button>
    </form>
</div>

{% if form.errors %}
    <ul>
        {% for error in form.errors %}
            <li>{{error}}</li>
        {% endfor %}
    </ul>
{% endif %}

<br>
<h3>holamundo</h3>

{% endblock content %}

app/my_app/templates/dashboard/evento/update.html
{% extends 'dashboard/base.html' %}



{% block title %}create_user{% endblock title %}

{% block content %}
<br>
<div class="container" >
    <form action="" method="post">
        {{ form.p_actual.label }}
        {{ form.p_actual }}
        {{ form.p_rezago.label }}
        {{ form.p_rezago }}
        {{ form.csrf_token }}
        <button type="submit">Enviar</button>
    </form>
</div>

{% if form.errors %}
    <ul>
        {% for error in form.errors %}
            <li>{{error}}</li>
        {% endfor %}
    </ul>
{% endif %}

<br>
<h3>holamundo</h3>

{% endblock content %}

app/my_app/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}



{% block title %}index{% endblock title %}

{% block content %}

<h3>Hola  "{{username}}" Actualizar datos. id {{user_id}} </h3><br> 
<br>
<table class="table" >
    <thead>
        <th>
            id
        </th>
        <th>
            username
        </th>
        <th>
            p_total
        </th>
        <th>
            p_actual
        </th>
        <th>
            p_rezago
        </th>
        <th>
            created_at
        </th>
    </thead>

    {% for x in b_id %}
    <tbody>
        <tr>
            <td>{{x.id}}</td>
            <td>{{x.area}}</td>
            <td>{{x.p_total}}</td>
            <td>{{x.p_actual}}</td>
            <td>{{x.p_rezago}}</td>
            <td>{{x.created_at}}</td>
        <td><a href="{{ url_for('simulacro.update',id=x.id) }}">edit</a></td>
        <td><a href="{{ url_for('simulacro.delete',id=x.id) }}">delete</a></td>
        </tr>
    </tbody>   
    {% endfor %}
</table>

{% endblock content %}

app/my_app/templates/dashboard/monitor.html
{% extends 'dashboard/base.html' %}



{% block title %}Monitor{% endblock title %}

{% block content %}

<h3>Hola  "{{username}}"  que tengas una buena noche...</h3><br> 

<table class="table" >
    <thead>
        <th>
            id
        </th>
        <th>
            username
        </th>
    </thead>

    {% for x in user %}
    <tbody>
        <tr>
            <td>{{x.id}}</td>
            <td>{{x.username}}</td>
        <td><a href="{{ url_for('simulacro.update',id=x.id) }}">edit</a></td>
        <td><a href="{{ url_for('simulacro.delete',id=x.id) }}">delete</a></td>
        </tr>
    </tbody>   
    {% endfor %}
</table>
{% endblock content %}

app/my_app/templates/dashboard/user/login.html
{% extends 'loginbase.html' %}

{% block title %}login{% endblock title %}



{% block content %}
<br>
<div class="container" >
    <ul>
        <form action="" method="post">
            {{ form.csrf_token }}
            <li>{{ form.username.label }}
                {{ form.username }}</li>
            <li>{{ form.password.label }}
                {{ form.password }}</li>      
            <button type="submit">Enviar</button>
        </form>
    </ul>
    
</div>

{% endblock content %}

app/my_app/templates/dashboard/user/register.html
{% extends 'loginbase.html' %}

{% block title %}Registrarse{% endblock title %}



{% block content %}
<br>
<div class="container" >
    <ul>
        <form action="" method="post">
            {{ form.csrf_token }}
            <li>{{ form.username.label }}
                {{ form.username }}</li>
            <li>{{ form.password.label }}
                {{ form.password }}</li>
            <li>{{ form.confirm.label }}
                {{ form.confirm }}</li>          
            <button type="submit">Enviar</button>
        </form>
    </ul>
    
</div>

{% if form.errors %}
    <ul>
        {% for error in form.errors %}
            <li>{{error}}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock content %}

app/my_app/templates/loginbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}{% endblock title %} </title>
</head>
<header>
</header>
<body>
    {{bootstrap.load_css()}}


    {% block content %}  
    {% endblock content %}

{{bootstrap.load_js()}}
</body>
</html>